create type "public"."color" as enum ('WHITE', 'BLACK');

create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "updated_at" timestamp with time zone not null default now(),
    "lobby_code" text not null,
    "last_move" text,
    "turn" color not null default 'WHITE'::color,
    "board_squares" jsonb not null default '[]'::jsonb,
    "pieces" jsonb not null default '[]'::jsonb,
    "settings" jsonb not null default '[]'::jsonb
);


alter table "public"."games" enable row level security;

create table "public"."lobbies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "lobby_code" text not null,
    "second_player" boolean not null default false,
    "game_started" boolean not null default false,
    "settings" jsonb not null default '[]'::jsonb
);


alter table "public"."lobbies" enable row level security;

CREATE UNIQUE INDEX "Lobbies_lobby_code_key" ON public.lobbies USING btree (lobby_code);

CREATE UNIQUE INDEX "Lobbies_pkey" ON public.lobbies USING btree (id);

CREATE UNIQUE INDEX games_id_key ON public.games USING btree (id);

CREATE UNIQUE INDEX games_lobby_id_key ON public.games USING btree (lobby_code);

CREATE UNIQUE INDEX games_pkey ON public.games USING btree (id);

alter table "public"."games" add constraint "games_pkey" PRIMARY KEY using index "games_pkey";

alter table "public"."lobbies" add constraint "Lobbies_pkey" PRIMARY KEY using index "Lobbies_pkey";

alter table "public"."games" add constraint "games_id_key" UNIQUE using index "games_id_key";

alter table "public"."games" add constraint "games_lobby_code_fkey" FOREIGN KEY (lobby_code) REFERENCES lobbies(lobby_code) not valid;

alter table "public"."games" validate constraint "games_lobby_code_fkey";

alter table "public"."games" add constraint "games_lobby_id_key" UNIQUE using index "games_lobby_id_key";

alter table "public"."lobbies" add constraint "Lobbies_lobby_code_key" UNIQUE using index "Lobbies_lobby_code_key";

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."lobbies" to "anon";

grant insert on table "public"."lobbies" to "anon";

grant references on table "public"."lobbies" to "anon";

grant select on table "public"."lobbies" to "anon";

grant trigger on table "public"."lobbies" to "anon";

grant truncate on table "public"."lobbies" to "anon";

grant update on table "public"."lobbies" to "anon";

grant delete on table "public"."lobbies" to "authenticated";

grant insert on table "public"."lobbies" to "authenticated";

grant references on table "public"."lobbies" to "authenticated";

grant select on table "public"."lobbies" to "authenticated";

grant trigger on table "public"."lobbies" to "authenticated";

grant truncate on table "public"."lobbies" to "authenticated";

grant update on table "public"."lobbies" to "authenticated";

grant delete on table "public"."lobbies" to "service_role";

grant insert on table "public"."lobbies" to "service_role";

grant references on table "public"."lobbies" to "service_role";

grant select on table "public"."lobbies" to "service_role";

grant trigger on table "public"."lobbies" to "service_role";

grant truncate on table "public"."lobbies" to "service_role";

grant update on table "public"."lobbies" to "service_role";


